# Chck env variables loading there is a problem here.
version: "3.9"
services:
  app:
    image: ruby-set
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./provision/Dockerfile
    command: /usr/src/docker_entrypoint.sh rails server -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
    depends_on:
      - db

  db:
    restart: always
    image: postgres:12.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - .:/usr/src

  # pgadmin:
  #   container_name: pgadmin-simpleapi
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   env_file:
  #     - .env
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db

volumes:
  db:
  # nodemodules: